### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [OperKH/kottans-js-2016#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by OperKH** [comment]
- [DevTools](http://i.imgur.com/GbA9fvl.png)
- [GitBranching](http://i.imgur.com/iIhj6l9.png)

**Comment by sudodoki** [comment]
LGTM
